### ISSUE TITLE
Incorporate Calendar style into themes?

### ISSUE THREAD

**Issue by mingyoungjeng** [mingyoungjeng/EECS448_Project3#14]
Just add a calendar object into the theme jsons and then change HistoryScreen.js to use style={global.style.calendar}

Thus, we can change the calendar's appearance based on the theme.

**Comment by johnportin** [comment]
Added a template for this. May been to pull marker styles directly from theme#.json since we can't seem to pull them from the stylesheet directly.

**Comment by johnportin** [comment]
themed markers have now been added.
