### ISSUE TITLE
No token data on History screen if not logged in

### ISSUE THREAD

**Issue by mingyoungjeng** [mingyoungjeng/EECS448_Project3#3]
<img width="1057" alt="Screen Shot 2021-04-18 at 5 41 44 PM" src="https://user-images.githubusercontent.com/35935981/115163284-ee9bcf00-a06d-11eb-81be-e2278b720aba.png">

**Comment by johnportin** [comment]
User is not logged in, so they do not have a token to authenticate.

Added a refection handler. Ideally, local user would be created and stored, but I don't know how to manage their data locally instead of through the database.
